# Generated by Django 4.2.1 on 2023-06-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phonen_number",
            new_name="phone_number",
        ),
    ]
